{
  "report_id": "UUID (Optional - generated by server if missing)",
  "device_id": "String (Required) - Unique ID of the sensor unit",
  "timestamp": "ISO 8601 String (Required) - e.g., '2026-02-11T14:30:00Z'",
  "location": {
    "latitude": "Decimal (Required) - e.g., 51.0447",
    "longitude": "Decimal (Required) - e.g., -114.0719",
    "gps_accuracy": "Float (Optional) - Accuracy in meters, e.g., 5.0"
  },
  "media": {
    "image_url": "String (Required) - URL to the blob in Azure Storage",
    "image_timestamp": "ISO 8601 String (Optional) - If different from report time"
  },
  "ai_analysis": {
    "detected_severity": "Integer (1-10) - Initial score by edge device",
    "confidence_score": "Float (0.0-1.0) - How sure the AI is"
  },
  "status": "String (Default: 'New') - [New, Verified, False_Positive, Scheduled, Repaired]"
}